import os
from PIL import Image
from dotenv import load_dotenv

import streamlit as st
import google.generativeai as genai
from google.generativeai.types import HarmCategory, HarmBlockThreshold

# =====================================================
# CONFIGURATION
# =====================================================

load_dotenv()

genai.configure(api_key=os.getenv("GEMINI_API_KEY"))

generation_config = {
    "temperature": 0.3,
    "top_p": 0.9,
    "max_output_tokens": 65536,
}

SYSTEM_PROMPT = """ 
You are Medical AI Assistant, a multimodal healthcare assistant designed to help analyze medical images and answer medical questions for educational and informational purposes. 

Your responsibilities are: 

1. Image Analysis - Carefully examine the uploaded medical image. 
- Describe the visible anatomical structures. 
- Identify any potentially abnormal findings or unusual visual patterns. 
- If the image quality is poor, explain why it limits the analysis. 

2. Findings 
- Summarize the important visual observations. 
- Explain each finding in clear, professional language. 
- Distinguish between observations and possible interpretations. 

3. Clinical Considerations 
- Suggest possible medical conditions that may be associated with the observed findings. 
- Never claim certainty or provide a definitive diagnosis. 
- Mention alternative possibilities when appropriate. 

4. Recommendations 
- Suggest appropriate next steps such as additional imaging, laboratory tests, or consultation with a qualified healthcare professional. 
- Recommend urgent medical attention if the image suggests a potentially serious condition. 

5. Communication Style 
- Use professional but easy-to-understand language. 
- Organize the response with clear headings and bullet points. 
- Explain medical terminology in simple language whenever possible. 

Important Guidelines: 
- Do not fabricate findings that are not visible in the image. 
- If the image is unclear or insufficient, state that additional information is required. 
- Never replace the judgment of a licensed healthcare professional. 
- Do not prescribe medications or treatment plans. 

Always end your response with this disclaimer: "This analysis is generated by AI for educational and informational purposes only. It is not a medical diagnosis and should not replace evaluation by a qualified healthcare professional." 

"""

# =====================================================
# LOAD MODEL (Cached)
# =====================================================

@st.cache_resource
def load_model():

    return genai.GenerativeModel(
        model_name="models/gemini-3-flash-preview",
        generation_config=generation_config,
        safety_settings={
            HarmCategory.HARM_CATEGORY_HARASSMENT:
                HarmBlockThreshold.BLOCK_ONLY_HIGH,

            HarmCategory.HARM_CATEGORY_HATE_SPEECH:
                HarmBlockThreshold.BLOCK_ONLY_HIGH,

            HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT:
                HarmBlockThreshold.BLOCK_ONLY_HIGH,

            HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT:
                HarmBlockThreshold.BLOCK_ONLY_HIGH,
        }
    )

model = load_model()

# =====================================================
# STREAMLIT UI
# =====================================================

st.set_page_config(
    page_title="Medical AI Assistant",
    page_icon="🩺",
    layout="centered"
)

st.title("🩺 Medical AI Assistant")

st.markdown(
    """
Upload a medical image (X-ray, MRI, CT Scan, Skin Image, etc.)
and receive an AI-generated analysis.

**Disclaimer:** This tool is for educational purposes only and
does not replace professional medical advice.
"""
)

uploaded_file = st.file_uploader(
    "Upload Medical Image",
    type=["png", "jpg", "jpeg"]
)

if uploaded_file:

    image = Image.open(uploaded_file)

    st.image(
        image,
        caption="Uploaded Image",
        use_container_width=True
    )

# =====================================================
# BUTTON
# =====================================================

if st.button("Generate Analysis"):

    if uploaded_file is None:

        st.warning("Please upload a medical image.")

    else:

        image = Image.open(uploaded_file)

        with st.spinner("Analyzing image with Gemini AI..."):

            try:

                response = model.generate_content(
                    [
                        SYSTEM_PROMPT,
                        image
                    ]
                )

                st.success("Analysis Complete")

                st.markdown("## AI Analysis")

                st.write(response.text)

            except Exception as e:

                st.error(f"Error: {e}")
